name: ğŸ±â€ğŸ’» Blog posts
on:
  schedule:
    - #runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's blog with latest blog post.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/check@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@hallyupesquisa"
          


